name: films_app_trainee_task
description: Flutter films app trainee task.
repository: https://github.com/StephaniOgu/films_app_trainee_task

version: 1.0.0+1

environment:
  sdk: '>=2.16.0 <3.0.0'
  flutter: '^2.10.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  get_it: ^7.2.0
  flutter_rating_bar: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
